version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        networks:
            - hrs-network

networks:
    hrs-network:
        driver: bridge
